const SMSG_SERVER_WELCOME = 0;
const CMSG_CLIENT_DATA = 1;
const SMSG_SESSION = 2;
const CMSG_SESSION_ACCEPTED = 3;
const SMSG_DATA_CHANGED = 4;
const SMSG_REGISTER_EVENT = 5;
const CMSG_GUI_EVENT = 6;
const CMSG_VALUE_CHANGE = 7;
const SMSG_TOAST = 8;
const SMSG_VIEW_FOR_INDEX = 9;
const CMSG_VIEW_FOR_INDEX = 10;
const SMSG_CHANGE_PAGE = 11;
const SMSG_DIALOG = 12;
const SMSG_LIST_REFRESH = 13;

const EVENT_TYPE_METHOD = 0;
const EVENT_TYPE_WATCH = 1;